apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: warden-observability
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: warden
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      protocol: TCP
