apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: warden-observability
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: warden
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tempo
  ports:
    - name: tempo-query
      port: 3200
      targetPort: 3200
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
